version: '3'
services:
  api:
    build:
      context: .
    command: npm run start:api:dev
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=api.sports-app.docker
      - VIRTUAL_PORT=3000
      - MANAGEMENT_URL=postgresql://postgres@db:5432/sportsapp
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sportsapp
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/sportsapp?sslmode=disable
    depends_on:
      - db
