name: CI Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Images
        run: docker-compose build
      - name: Install
        run: docker-compose run --rm api npm ci
      - name: Bootstrap
        run: docker-compose run --rm api npx lerna bootstrap
      - name: Lint
        run: docker-compose run --rm api npm run lint
      - name: Check for uncommitted changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Fail if there are uncommitted changes
        if: steps.changes.outputs.changed == 1
        run: git status && exit 1
      - name: Build
        run: docker-compose run --rm api run build
      - name: Test
        run: docker-compose run --rm api npm run test
