name: CI Build
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: docker-compose run --rm api npm run lint
      - name: Test
        run: docker-compose run --rm api npm run test
